#!/bin/bash
ALACRITTY_CONF="$HOME/.config/alacritty/alacritty.toml"

case "$1" in
  l*)
    THEME=papertheme
    OPACITY=1.0
    ;;
  d*)
    THEME=taerminal
    OPACITY=0.95
    ;;
  *) exit 1 ;;
esac

sed -i -re "/config\/alacritty\/themes/ s/(\/themes\/themes\/)(\w+)\.toml/\1${THEME}.toml/" ${ALACRITTY_CONF}
sed -i -r "s/(^opacity = )(.*)/\1${OPACITY}/" ${ALACRITTY_CONF}

